esphome:
  name: c6-1
  friendly_name: C6-1

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "i4GEBQQKanq/cDp7gFpTAQ8O05vxtkACNga18/tqx20="

ota:
  - platform: esphome
    password: "7aa17843805ac83b1d5bd7a404dff28c"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "C6-1 Fallback Hotspot"
    password: "i4TFYFmEWhAV"

captive_portal:
    
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/London
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

mqtt:
  broker: 192.168.11.1
  port: 1883
  username: esphome
  password: esphomepassword
  client_id: c6-1

    
sensor:
  - platform: dht
    pin: 0
    temperature: 
      name: Temp 
    humidity: 
      name: Hum 
    update_interval: 10s
  - platform: ultrasonic
    trigger_pin: 3
    echo_pin: 2
    name: "Ultrasonic Sensor"
    update_interval: 5s
