esphome:
  name: candi-esp-1

esp32:
  board: upesy_wroom
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "MA37WJKp/U5mG4SB3jl6E5+ZxrB/0dMn6LENyrpz+kk="

ota:
  - platform: esphome


wifi:
  ssid: "CANDI"
  password: "bruteforcethis"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Candi-Esp-1 Fallback Hotspot"
    password: "nTChn1bAUBwt"

captive_portal:
    